<!-- <div class="parallax">
    <header id="hero-header">
        <span>
            <img src="../public/assets/img/flower-white-line.svg"/>
        </span>    
        <span>    
            <nav>
                <a href="#presentation">Présentation</a>
                <a href="?p=projets">Projets</a>
                <a href="#contact">Contact</a>
            </nav>
        <span>
    </header>
    <div id="hero">
        <H1>Audrey Norvez, développeuse web.</h1>
        <p>En reconversion professionnelle, j’ai intégré le bachelor de My Digital School qui me forme aux métiers du numérique. Aujourd’hui en deuxième année, j’ai choisi de me spécialiser dans le développement.</p>
    </div>
    <img  src="../public/assets/img/hero.png">
    <img id="parallax-11" class="parallax-background" src="../public/assets/img/parallax/11_background.png">
    <img id="parallax-10" class="parallax-background" src="../public/assets/img/parallax/10_clouds.png">
    <img id="parallax-09" class="parallax-back" src="../public/assets/img/parallax/9_back.png">
    <img id="parallax-08" class="parallax-back width70" src="../public/assets/img/parallax/8_back.png">
    <img id="parallax-07" class="parallax-back width70" src="../public/assets/img/parallax/7_back.png">
    <img id="parallax-06" class="parallax-back width70" src="../public/assets/img/parallax/6_back.png">
    <img id="parallax-05" class="parallax-background" src="../public/assets/img/parallax/5_water.png">
    <img id="parallax-04" class="parallax-front" src="../public/assets/img/parallax/4_front.png">
    <img id="parallax-03" class="parallax-front width70" src="../public/assets/img/parallax/3_front.png">
    <img id="parallax-02" class="parallax-front width70" src="../public/assets/img/parallax/2_front.png">
    <img id="parallax-01" class="parallax-front" src="../public/assets/img/parallax/1_front.png">
</div> -->

<div class="parallax">
    <header class="primary-header">
        <div id="hero-header">
            <div class="primary-header__inner">
                <div class="logo">
                    <a href="?v=">
                        <img src="../public/assets/img/flower-white-line.svg" alt="" />
                    </a>
                </div>
                <nav class="primary-nav">
                    <ul role="list">
                        <li class="scrollTo scrollToLifeSection"><a>Présentation</a></li>
                        <li><a href="?v=projects">Projets</a></li>
                        <li class="scrollTo scrollToContactSection"><a>Contact</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div class="hero">
        <div class="wrapper">
            <H1>Audrey Norvez, développeuse web.</h1>
            <p>En reconversion professionnelle, j’ai intégré le bachelor de My Digital School qui me forme aux métiers du numérique. Aujourd’hui en deuxième année, j’ai choisi de me spécialiser dans le développement.</p>
            <div class="buttons">
                <a href="https://www.linkedin.com/in/audrey-norvez-a25673253/" target="_blank" class="Button PrimaryPinkButton">Mes actus</a>
                <a onclick="window.open('https://drive.google.com/file/d/1vE8P0IgKtdgiQYVRpTlWnV7DvUQm6HGQ/view?usp=drive_link','_blank');" class="Button SecondaryPinkButton">Découvrir mon CV</a>
            </div>
        </div>
    </div>
    <img class="parallax__bg" src="../public/assets/img/hero.png">
</div>

<div id="btnScrollToLifeSection" class="flex">
    <img id="imgScrollDown" class="scrollTo scrollToLifeSection"  src="../public/assets/img/arrow.svg" alt="bouton pour découvrir mon parcours"/>
</div>

<a id="scrollToTop" class="flex">
    <img id="imgUpToTop" src="../public/assets/img/arrow.svg" alt="bouton pour remonter en haut de la page"/>
</a>

<main>
    <section id="life">
        <h2>Mon parcours</h2>
        <div id="arrow-date" class="flex">
        </div>
        <div id="bloc-date">
            <h3>De 2016 à aujourd'hui : suivez mes pas, année après année</h3>
            <div class="flex">
                <img class="icon" src="../public/assets/img/icons/school.png">
                <p>Je vous présenterais mon parcours scolaire, les compétences que j'ai acquises.</p>
            </div>
            <div class="flex">
                <img class="icon" src="../public/assets/img/icons/work.png">
                <p>Mais aussi mon chemin professionnel, très varié, qui m'a fais grandir et avancer.</p>
            </div>
            <div class="flex">
                <img class="icon" src="../public/assets/img/icons/idea.png">
                <p>Enfin, tous les <i>softs skills</i> que ces expériences m'ont apporté et que j'ai développer.</p>
            </div>
        </div>
    </section>
    
    <section id="skills">
        <div>
            <h2>Mes compétences</h2>
            <P>Depuis mon entrée à My Digital School,  j’ai eu l’occasion de développer des compétences en web design, par la réalisation de chartes graphiques, de logo, de maquettes mais aussi d’affiches, de posts réseaux...<br>J’ai également appris différents langages et outils ce qui m’a permis de réaliser plusieurs projets comme des sites vitrines, e-commerce ou des blogs.</P>
            <a onclick="window.open('https://drive.google.com/file/d/1vE8P0IgKtdgiQYVRpTlWnV7DvUQm6HGQ/view?usp=drive_link','_blank');" class="Button SecondaryPinkButton">Découvrir mon CV</a>
        </div>
        <div>
            <img class="bubble" src="../public/assets/img/bulles/bulle-dev.png">
            <img class="bubble" src="../public/assets/img/bulles/bulle-wp.png">
            <img class="bubble" src="../public/assets/img/bulles/bulle-design.png">
        </div>
    </section>

    <section id="projects">
        <h2>Mes réalisations</h2>
        <p>Voici quelques projets réalisés depuis mon entrée en première année.</p>
        <div>
            <div class="flex wrap wrap-project">
                <?php foreach ($data as $project): ?>
                    <a href="http://localhost/portfolio/public/?v=project&p=<?=$project['ID'];?>">
                        <div class="project" style="background-color:#<?=$project['primary_color'];?>;">
                            <div class="flex contain-logo">
                                <img src="../public/assets/img/projects/<?=$project['logo'];?>">
                            </div>
                            <div class="contain-project">
                                <h3><?=$project['name'];?></h3>
                                <div class="buttons">
                                    <p class="tag"><?=$project['tag_first'];?></p>
                                    <p class="tag"><?=$project['tag_second'];?></p>
                                    <p class="tag"><?=$project['tag_third'];?></p>
                                </div>
                            </div>
                        </div>
                    </a>
                <?php endforeach ?>
            </div>
            <div class="flex wrap-project">
                <a href="./?v=projects" class="Button PrimaryPinkButton">Voir tous mes projets</a>
            </div>
        </div>
    </section>
</main>