  <footer id="contact">
    <div>
      <h3>On se rencontre ?</h3>
      <p>N’hésitez pas à me contacter si vous souhaitez en savoir plus ! Je suis également à la recherche d’une alternance pour ma troisième année de bachelor Développeur Web.</p>
      <div class="buttons">
        <a class="Button SecondaryBlueButton" target="_blank" href="mailto:contact@audreynorvez.fr">contact@audreynorvez.fr</a>
        <a class="Button PrimaryBlueButton" target="_blank" href="https://wa.me/0634213227">06 34 21 32 27</a>
      </div>
    </div>
    <div>
      <p>Audrey Norvez © 2024</p>
    </div>
</footer>
<script src="../public/assets/script.js" type="text/javascript"></script>
</body>
</html>