<header class="scrolling-header primary-header" style="display:block">
  <div id="hero-header">
    <div class="primary-header__inner">
      <div class="logo">
        <a href="?v=">
          <img src="../public/assets/img/flower-white-line.svg" alt="" />
        </a>
      </div>
      <nav class="primary-nav">
        <ul role="list">
          <li><a href="./#life">Présentation</a></li>
          <li><a href="?v=projects">Projets</a></li>
          <li class="scrollTo scrollToContactSection"><a>Contact</a></li>
        </ul>
      </nav>
    </div>
  </div>
</header>