<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../public/assets/css/main.css" rel="stylesheet"/>
    <link rel="icon" size="16x16" type="image" href="assets/img/favicon.svg"/>
    <title>Audrey Norvez</title>
</head>
<body>
    <header id="scrolling-header">
        <img src="../public/assets/img/flower-white-line.svg"/>
        <nav>
            <a href="#life">Présentation</a>
            <a href="?p=projets">Projets</a>
            <a href="#contact">Contact</a>
        </nav>
    </header>